In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df=pd.read_csv('Online-Store-Orders.csv')
df.head(50)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52
10,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
11,ORD200011,2024-02-17,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
12,ORD200012,2024-10-15,C38785,Monitor,2,180.50,179 Main St,Debit Card,Pending,TRK20419991,6,FREESHIP,Referral,361.00
13,ORD200013,2023-08-30,C88348,Laptop,3,201.49,903 Main St,Credit Card,Returned,TRK81913874,4,FREESHIP,Facebook,604.47
14,ORD200014,2023-03-27,C98474,Tablet,2,393.33,980 Main St,Debit Card,Pending,TRK79186539,3,SAVE10,Instagram,786.66
15,ORD200015,2023-07-17,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,NaN,Google,473.96
16,ORD200016,2023-01-24,C28976,Printer,2,533.81,914 Main St,Credit Card,Pending,TRK13194259,3,FREESHIP,Email,1067.62
17,ORD200017,2024-03-02,C60672,Tablet,1,423.40,382 Main St,Debit Card,Shipped,TRK11972116,3,NaN,Referral,423.40
18,ORD200018,2025-03-26,C84329,Desk,1,431.44,891 Main St,Gift Card,Pending,TRK65191045,3,SAVE10,Facebook,431.44
19,ORD200019,2023-01-23,C14552,Monitor,5,224.00,273 Main St,Cash,Returned,TRK59101365,9,SAVE10,Google,1120.00
20,ORD200020,2023-05-08,C54829,Chair,5,62.51,587 Main St,Cash,Pending,TRK16718651,9,WINTER15,Instagram,312.55
21,ORD200021,2024-11-17,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,NaN,Google,1371.80
22,ORD200022,2023-01-29,C34416,Monitor,2,49.62,633 Main St,Online,Pending,TRK75937350,2,SAVE10,Google,99.24
23,ORD200023,2025-04-09,C42372,Phone,4,273.25,755 Main St,Debit Card,Cancelled,TRK36168083,5,FREESHIP,Referral,1093.00
24,ORD200024,2024-10-30,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
25,ORD200025,2024-07-24,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
26,ORD200026,2024-03-06,C21944,Laptop,5,59.55,296 Main St,Online,Delivered,TRK80276812,6,NaN,Referral,297.75
27,ORD200027,2024-02-22,C97593,Printer,1,472.74,881 Main St,Online,Shipped,TRK89117573,6,WINTER15,Google,472.74
28,ORD200028,2023-11-21,C59823,Phone,4,160.07,568 Main St,Online,Pending,TRK65895539,5,NaN,Email,640.28
29,ORD200029,2024-09-20,C33260,Desk,3,423.53,930 Main St,Credit Card,Delivered,TRK59744090,6,SAVE10,Referral,1270.59
30,ORD200030,2025-03-22,C44267,Monitor,2,426.70,895 Main St,Online,Pending,TRK54751444,5,SAVE10,Referral,853.40
31,ORD200031,2023-06-30,C26445,Chair,3,500.08,996 Main St,Debit Card,Returned,TRK31229981,6,NaN,Facebook,1500.24
32,ORD200032,2023-05-01,C12388,Tablet,5,536.72,830 Main St,Cash,Delivered,TRK99261395,10,NaN,Email,2683.60
33,ORD200033,2023-06-05,C52184,Chair,1,162.77,912 Main St,Online,Cancelled,TRK73312471,4,WINTER15,Facebook,162.77
34,ORD200034,2023-01-07,C67195,Chair,4,576.52,926 Main St,Credit Card,Pending,TRK55467915,5,WINTER15,Facebook,2306.08
35,ORD200035,2024-12-07,C50304,Monitor,2,465.15,128 Main St,Online,Shipped,TRK46850888,2,SAVE10,Facebook,930.30
36,ORD200036,2025-05-08,C59337,Laptop,2,534.43,465 Main St,Debit Card,Pending,TRK50961250,5,NaN,Facebook,1068.86
37,ORD200037,2024-10-14,C10054,Laptop,2,76.74,409 Main St,Cash,Returned,TRK94005261,7,SAVE10,Instagram,153.48
38,ORD200038,2024-12-19,C15924,Laptop,1,245.89,549 Main St,Debit Card,Delivered,TRK14835975,3,SAVE10,Google,245.89
39,ORD200039,2025-02-27,C96664,Printer,3,256.46,666 Main St,Credit Card,Delivered,TRK85508960,4,SAVE10,Referral,769.38
40,ORD200040,2023-08-20,C84766,Desk,2,344.02,267 Main St,Online,Delivered,TRK78967923,4,FREESHIP,Instagram,688.04
41,ORD200041,2023-12-05,C20212,Monitor,3,611.45,657 Main St,Gift Card,Pending,TRK69733327,4,FREESHIP,Instagram,1834.35
42,ORD200042,2024-05-06,C28712,Printer,2,151.66,980 Main St,Cash,Cancelled,TRK40772558,6,NaN,Instagram,303.32
43,ORD200043,2023-12-14,C60572,Chair,3,499.21,871 Main St,Online,Cancelled,TRK20351666,8,NaN,Instagram,1497.63
44,ORD200044,2025-04-21,C73225,Phone,2,550.18,996 Main St,Gift Card,Returned,TRK73848522,3,FREESHIP,Referral,1100.36
45,ORD200045,2024-02-10,C17388,Chair,1,317.25,157 Main St,Debit Card,Returned,TRK47077395,1,SAVE10,Facebook,317.25
46,ORD200046,2024-06-26,C43212,Monitor,4,550.14,223 Main St,Debit Card,Pending,TRK25100762,4,FREESHIP,Instagram,2200.56
47,ORD200047,2023-07-19,C38134,Desk,2,209.94,323 Main St,Credit Card,Returned,TRK42450754,3,FREESHIP,Email,419.88
48,ORD200048,2023-08-26,C12408,Monitor,2,80.77,464 Main St,Debit Card,Shipped,TRK38938858,4,NaN,Google,161.54
49,ORD200049,2023-10-07,C11985,Printer,1,30.44,633 Main St,Credit Card,Shipped,TRK53272402,1,SAVE10,Email,30.44

In [19]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [20]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [21]:
df['CouponCode'].head(50)

0       SAVE10
1       SAVE10
2     FREESHIP
3       SAVE10
4       SAVE10
5       SAVE10
6       SAVE10
7     FREESHIP
8          NaN
9       SAVE10
10    WINTER15
11      SAVE10
12    FREESHIP
13    FREESHIP
14      SAVE10
15         NaN
16    FREESHIP
17         NaN
18      SAVE10
19      SAVE10
20    WINTER15
21         NaN
22      SAVE10
23    FREESHIP
24    WINTER15
25    WINTER15
26         NaN
27    WINTER15
28         NaN
29      SAVE10
30      SAVE10
31         NaN
32         NaN
33    WINTER15
34    WINTER15
35      SAVE10
36         NaN
37      SAVE10
38      SAVE10
39      SAVE10
40    FREESHIP
41    FREESHIP
42         NaN
43         NaN
44    FREESHIP
45      SAVE10
46    FREESHIP
47    FREESHIP
48         NaN
49      SAVE10
Name: CouponCode, dtype: object

In [22]:
df['CouponCode']=df['CouponCode'].fillna('No Coupon')

In [23]:
df['CouponCode'].head(50)

0        SAVE10
1        SAVE10
2      FREESHIP
3        SAVE10
4        SAVE10
5        SAVE10
6        SAVE10
7      FREESHIP
8     No Coupon
9        SAVE10
10     WINTER15
11       SAVE10
12     FREESHIP
13     FREESHIP
14       SAVE10
15    No Coupon
16     FREESHIP
17    No Coupon
18       SAVE10
19       SAVE10
20     WINTER15
21    No Coupon
22       SAVE10
23     FREESHIP
24     WINTER15
25     WINTER15
26    No Coupon
27     WINTER15
28    No Coupon
29       SAVE10
30       SAVE10
31    No Coupon
32    No Coupon
33     WINTER15
34     WINTER15
35       SAVE10
36    No Coupon
37       SAVE10
38       SAVE10
39       SAVE10
40     FREESHIP
41     FREESHIP
42    No Coupon
43    No Coupon
44     FREESHIP
45       SAVE10
46     FREESHIP
47     FREESHIP
48    No Coupon
49       SAVE10
Name: CouponCode, dtype: object

#Replaced 309 missing values with "No Coupon".
#In an online store environment, a missing coupon code often indicates that no promotional code was applied during checkout.
#This preserved all transaction records while making the column easier to analyze.

In [24]:
duplicate_ids = df['OrderID'].duplicated().sum()

print(f"Duplicate Order IDs: {duplicate_ids}")

Duplicate Order IDs: 0